
base_llm:
  # Model - one of ["gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-3.5-turbo-0613", "gpt-4", "gpt-4-0613"]
  model: "gpt-4"
  temperature: 0.0
  streaming: true

langchain:
  tracing: true
  debug: false
  verbose: true